enum API_ENUM {
  SIGNUP,
  LOGIN,
  GET_USER_INFO,
  LOGOUT,
  PROVIDER_GET_REQUEST,
  PROVIDER_ADD_SERVICE,
  PROVIDER_UPDATE_AVAILABILITY,
  PROVIDERS_BY_CATEGORY,
  CLIENT_SERVICE_BOOKING
}

export default API_ENUM;
